plugins {
    id 'java'
}

group = 'nekonic'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}


dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT'
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

jar {
    archiveFileName = 'Mineconomy-GUI.jar'
    if (!System.getenv("CI")) { // if not GitHub Actions
        destinationDirectory = file("/home/nekonic/1server/plugins")
    }
}

tasks.withType(JavaCompile){
    options.encoding = "UTF-8"
}
